import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/base/app-sidebar";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider className="p-4">
          <AppSidebar />
          <div className="flex flex-col w-full gap-4">
            <Card className="w-full h-fit ">
              <CardContent className="grid grid-cols-2 ">
                <img
                  className="rounded-lg size-12 object-cover"
                  src="/file.svg"
                />
                <CardDescription className="flex justify-start items-center">
                  fjhslknsdfjklbnsfblkjnsdbkljnsdfblnsdjkflbnkdfn
                </CardDescription>
              </CardContent>
            </Card>
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
