import type { Metadata } from "next";
import { resturant } from "@/data";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/base/app-sidebar";
import { Card, CardContent, CardDescription } from "@/components/ui/card";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider className="p-4">
          <AppSidebar />
          <div className="flex flex-col w-full gap-4">
            <Card className="w-full h-fit ">
              <CardContent className="grid grid-cols-3 ">
                <div className="flex justify-center">
                  <img
                    className="rounded-full size-16 object-cover"
                    src={resturant.default_data.logo}
                    alt="logo"
                  />
                </div>
                <CardDescription className="flex  items-center justify-center text-pink-900">
                  {resturant.default_data.name}
                </CardDescription>
                <CardDescription className="flex justify-center items-center text-pink-900">
                  {resturant.default_data.slogan}
                </CardDescription>
              </CardContent>
            </Card>
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
